from importlib.metadata import PackageNotFoundError, version as _package_version

from ._errors import (
    APIError,
    AuthError,
    BadRequestError,
    ERLCError,
    InvalidCommandError,
    ModelDecodeError,
    ModuleOutdatedError,
    NetworkError,
    NotFoundError,
    PermissionDeniedError,
    ProhibitedMessageError,
    RateLimitError,
    RestrictedCommandError,
    RobloxCommunicationError,
    ServerOfflineError,
)
from .client import AsyncClient, AsyncERLC, Client, ERLC, ValidationResult, ValidationStatus
from .commands import (
    Command,
    CommandMetadata,
    CommandPreview,
    CommandPolicy,
    CommandPolicyError,
    CommandPolicyResult,
    cmd,
    get_command_metadata,
    normalize_command,
    preview_command,
    validate_command,
)
from .models import (
    BanEntry,
    BanList,
    CommandLogEntry,
    CommandResult,
    EmergencyCall,
    JoinLogEntry,
    KillLogEntry,
    ModCallEntry,
    PermissionLevel,
    Player,
    PlayerLocation,
    ServerBundle,
    ServerInfo,
    ServerLogs,
    StaffList,
    StaffMember,
    Vehicle,
    VehicleColor,
    parse_player_identifier,
)

try:
    __version__ = _package_version("erlc-api.py")
except PackageNotFoundError:
    __version__ = "3.1.0"

__all__ = [
    "APIError",
    "AsyncClient",
    "AsyncERLC",
    "AuthError",
    "BadRequestError",
    "BanEntry",
    "BanList",
    "Command",
    "CommandMetadata",
    "CommandPreview",
    "CommandPolicy",
    "CommandPolicyError",
    "CommandPolicyResult",
    "CommandLogEntry",
    "CommandResult",
    "Client",
    "ERLC",
    "ERLCError",
    "EmergencyCall",
    "InvalidCommandError",
    "JoinLogEntry",
    "KillLogEntry",
    "ModCallEntry",
    "ModelDecodeError",
    "ModuleOutdatedError",
    "NetworkError",
    "NotFoundError",
    "PermissionDeniedError",
    "PermissionLevel",
    "Player",
    "PlayerLocation",
    "ProhibitedMessageError",
    "RateLimitError",
    "RestrictedCommandError",
    "RobloxCommunicationError",
    "ServerBundle",
    "ServerInfo",
    "ServerLogs",
    "ServerOfflineError",
    "StaffList",
    "StaffMember",
    "ValidationResult",
    "ValidationStatus",
    "Vehicle",
    "VehicleColor",
    "cmd",
    "get_command_metadata",
    "__version__",
    "normalize_command",
    "parse_player_identifier",
    "preview_command",
    "validate_command",
]
