# src/erlc_api/__init__.py
from .client import ERLCClient
from .client import ValidationResult, ValidationStatus
from .commands import BuiltCommand, CommandBuilder, validate_command_syntax
from .context import ERLCContext, fingerprint_key
from ._errors import (
    APIError,
    AuthError,
    CircuitOpenError,
    ERLCError,
    InvalidCommandError,
    ModelDecodeError,
    NetworkError,
    NotFoundError,
    PermissionDeniedError,
    PlayerNotFoundError,
    RateLimitError,
    RobloxCommunicationError,
    ServerEmptyError,
)
from .models import (
    BanEntry,
    CommandLogEntry,
    CommandResponse,
    EmergencyCall,
    JoinLogEntry,
    KillLogEntry,
    ModCallEntry,
    Player,
    PlayerLocation,
    QueueEntry,
    ServerInfo,
    StaffMember,
    V2ServerBundle,
    Vehicle,
    VehicleColor,
)
from .tracking import ServerState, ServerTracker, TrackerEvent
from .validated import V2ServerBundleValidated, decode_v2_server_bundle_validated
from .webhooks import (
    PRC_EVENT_WEBHOOK_PUBLIC_KEY_SPKI_B64,
    CustomCommandInvocation,
    EventWebhookRouter,
    InvalidWebhookSignatureError,
    MissingWebhookHeaderError,
    UnsupportedWebhookEventError,
    WebhookError,
    WebhookEvent,
    WebhookEventType,
    WebhookSignatureHeaders,
    assert_valid_event_webhook_signature,
    decode_event_webhook_payload,
    extract_webhook_signature_headers,
    parse_custom_command_text,
    verify_event_webhook_signature,
)

__all__ = [
    "ERLCClient",
    "ERLCContext",
    "ValidationResult",
    "ValidationStatus",
    "fingerprint_key",
    "CommandBuilder",
    "BuiltCommand",
    "validate_command_syntax",
    "ERLCError",
    "APIError",
    "AuthError",
    "NetworkError",
    "NotFoundError",
    "RateLimitError",
    "PermissionDeniedError",
    "PlayerNotFoundError",
    "ServerEmptyError",
    "RobloxCommunicationError",
    "InvalidCommandError",
    "CircuitOpenError",
    "ModelDecodeError",
    "CommandResponse",
    "ServerInfo",
    "Player",
    "PlayerLocation",
    "StaffMember",
    "QueueEntry",
    "JoinLogEntry",
    "KillLogEntry",
    "CommandLogEntry",
    "ModCallEntry",
    "Vehicle",
    "VehicleColor",
    "EmergencyCall",
    "BanEntry",
    "V2ServerBundle",
    "ServerState",
    "ServerTracker",
    "TrackerEvent",
    "V2ServerBundleValidated",
    "decode_v2_server_bundle_validated",
    "WebhookError",
    "MissingWebhookHeaderError",
    "InvalidWebhookSignatureError",
    "UnsupportedWebhookEventError",
    "WebhookEventType",
    "WebhookSignatureHeaders",
    "CustomCommandInvocation",
    "WebhookEvent",
    "EventWebhookRouter",
    "PRC_EVENT_WEBHOOK_PUBLIC_KEY_SPKI_B64",
    "extract_webhook_signature_headers",
    "verify_event_webhook_signature",
    "assert_valid_event_webhook_signature",
    "decode_event_webhook_payload",
    "parse_custom_command_text",
]
